# Site settings
title: Code Bender
email: joe@wanat.com
description: "Joe Wanat: Hockey player, adventure seeker, adrenaline junky."
baseurl: ""
url: "http://jjwanat.github.io"
twitter_username: JoeWanat
github_username:  jjwanat
facebook_username:  joe.wanat.3

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]
