# Site settings
title: Joe Wanat
email: joe@wanat.com
description: "Hockey player, adventure seeker, adrenaline junky."
baseurl: ""
url: "http://jjwanat.github.io"
twitter_username: JoeWanat
github_username:  jjwanat
facebook_username:  Joe Wanat

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]
