name: Joe Wanat
markdown: redcarpet
pygments: true
github: jjwanat.github.io
about: I am an aspiring developer. I dabble with Ruby, Python, JS, and more. Love adventure and traveling, gadgets, cooking, and life. Retired hockey player.
urls:
    - text: github
      url: https://github.com/jjwanat
    - text: twitter
      url: https://twitter.com/joewanat
    - text: email
      url: mailto:wanat.joe@gmail.com
